/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_desensitize_EncryptUtil */

#ifndef _Included_com_desensitize_EncryptUtil
#define _Included_com_desensitize_EncryptUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_desensitize_EncryptUtil
 * Method:    doEncryptData1
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_desensitize_EncryptUtil_doEncryptData1
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_desensitize_EncryptUtil
 * Method:    doEncryptData2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_desensitize_EncryptUtil_doEncryptData2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_desensitize_EncryptUtil
 * Method:    doEncryptData3
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_desensitize_EncryptUtil_doEncryptData3
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
